version: 2
builds:
  - id: ntwire
    main: ./cmd/ntwire
    binary: ntwire
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
  - id: ntwire-server
    main: ./cmd/ntwire-server
    binary: ntwire-server
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
archives:
  - format_overrides: [{goos: windows, format: zip}]
