version: 2
builds:
  - id: nwire
    main: ./cmd/nwire
    binary: nwire
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
  - id: nwire-server
    main: ./cmd/nwire-server
    binary: nwire-server
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
archives:
  - format_overrides: [{goos: windows, format: zip}]
