apiVersion: v1
kind: Service
metadata: {name: nwire-server}
spec:
  selector: {app: nwire-server}
  ports: [{name: https, port: 8443, targetPort: https}, {name: wireguard, port: 51820, targetPort: wireguard, protocol: UDP}]
